[build]
publish = "publish"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "false"

[context.deploy-preview.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENABLEGITINFO = "true"
